OdeToFood/Entities/OdeToFoodDbContext.cs
using Microsoft.EntityFrameworkCore;
using OdeToFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Entities
{
    public class OdeToFoodDbContext : DbContext
    {
        public OdeToFoodDbContext(DbContextOptions options)
            : base (options)
        {
        }

        public DbSet<Restaurant> Restaurants { get; set; }
    }
}

OdeToFood/Models/CuisineType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Models
{
    public enum CuisineType
    {
        None,
        Italian,
        French,
        German
    }
}

OdeToFood/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Models
{
    public class Restaurant
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(80)]
        [Display(Name="Restaurant Name")]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

OdeToFood/ViewModels/HomeIndexVM.cs
using OdeToFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewModels
{
    public class HomeIndexVM
    {
        public IEnumerable<Restaurant> Restaurants { get; set; }
        public string MessageOfTheDay { get; set; }
    }
}

OdeToFood/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OdeToFood.Controllers
{
    //[Route("about")]
    [Route("company/[controller]/[action]")]
    public class AboutController
    {
        //[Route("")]
        public string Phone()
        {
            return "+1+555+333+5555";
        }

        //[Route("address")]
        public string Address()
        {
            return "USA";
        }
    }
}

OdeToFood/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Models;
using OdeToFood.Services;
using OdeToFood.ViewModels;

namespace OdeToFood.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRestaurantData restaurantData;
        private readonly IGreeter greeter;

        public HomeController(IRestaurantData restaurantData, IGreeter greeter)
        {
            this.restaurantData = restaurantData;
            this.greeter = greeter;
        }

        public IActionResult Index()
        {
            var model = new HomeIndexVM();
            model.Restaurants = this.restaurantData.GetAll();
            model.MessageOfTheDay = this.greeter.GetMessageOfTheDay();

            //this.HttpContext.Response.ContentType = "application/json";
            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = this.restaurantData.Get(id);
            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(model);

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Restaurant input)
        {
            if (this.ModelState.IsValid)
            {
                var model = this.restaurantData.Add(input);
                this.restaurantData.SaveChanges();

                return RedirectToAction(nameof(Details), new { id = model.Id });
            }
            else
            {
                // redisplay the form and show the validation errors from ModelState
                return View();
            }
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var model = this.restaurantData.Get(id);
            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Restaurant input)
        {
            if (this.ModelState.IsValid)
            {
                var model = this.restaurantData.Update(input);
                this.restaurantData.SaveChanges();

                return RedirectToAction(nameof(Details), new { id = model.Id /*, foo = "bar"*/ }); // foo will be placed in the query string
            }
            else
            {
                // redisplay the form and show the validation errors from ModelState
                return View();
            }
        }
    }
}

OdeToFood/Pages/Greeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Services;

namespace OdeToFood.Pages
{
    public class GreetingModel : PageModel
    {
        private readonly IGreeter _greeter;
        public string CurrentMessage { get; set; }

        public GreetingModel(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public void OnGet(string name)
        {
            CurrentMessage = $"{name}: {_greeter.GetMessageOfTheDay()}";
        }
    }
}

OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Models;
using OdeToFood.Services;

namespace OdeToFood.Pages.Restaurants
{
    public class EditModel : PageModel
    {
        private readonly IRestaurantData _restaurantData;

        [BindProperty]
        public Restaurant Restaurant { get; set; }

        public EditModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }

        public IActionResult OnGet(int id)
        {
            Restaurant = _restaurantData.Get(id);
            if (Restaurant == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                Restaurant = _restaurantData.Update(Restaurant);
                _restaurantData.SaveChanges();

                return RedirectToAction("Details", "Home", new { id = Restaurant.Id });
            }
            else
            {
                return Page();
            }
        }
    }
}

OdeToFood/ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private readonly IGreeter _greeter;

        public GreeterViewComponent(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetMessageOfTheDay();

            return View("Default", model);
        }
    }
}

OdeToFood/Pages/Greeting.cshtml
@page "{name}"
@model GreetingModel
@{
    ViewData["Title"] = "Greeting";
}
@*@inject IGreeter Greeter
    <h2>Greeting: @Greeter.GetMessageOfTheDay()</h2>*@

<h2>@Model.CurrentMessage</h2>

OdeToFood/Pages/Restaurants/Edit.cshtml
@page
@using OdeToFood.Pages.Restaurants

@model EditModel

@{
    ViewBag.Title = "Update " + @Model.Restaurant.Id.ToString();
}

<h1>Update @Model.Restaurant.Name</h1>

<form method="post">
    <input type="hidden" asp-for="Restaurant.Id" />

    <div>
        <label asp-for="Restaurant.Name" />
        <input asp-for="Restaurant.Name" />
        <span asp-validation-for="Restaurant.Name"></span>
    </div>
    <div>
        <label asp-for="Restaurant.Cuisine" />
        <select asp-for="Restaurant.Cuisine" asp-items="Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Restaurant.Cuisine"></span>
    </div>
    <input type="submit" name="Save" value="Save" />
</form>

OdeToFood/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <div>
        Copyright: @DateTime.Now.Year
    </div>
    <footer>
        @RenderSection("footer", required:false)
    </footer>
</body>
</html>

OdeToFood/Views/Home/Create.cshtml
@model Restaurant

@{ 
    ViewBag.Title = "Create";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>
<form method="post">
    <div>
        <label asp-for="Name" />
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <select asp-for="Cuisine" asp-items="Html.GetEnumSelectList<CuisineType>()"></select>
    </div>
    <input type="submit" name="Save" value="Save" />
</form>

OdeToFood/Views/Home/Details.cshtml
@model Restaurant

@{
    ViewBag.Title = "Details for Restaurant " + Model.Id.ToString();
}
<body>
    <div>
        <h1>@Model.Id</h1>
        <h1>@Model.Name</h1>
        <p>Other details...</p>
        @*<p>@Html.ActionLink("<- Home", "Index", "Home")</p>*@
        <a asp-action="Index" asp-controller="Home">Turn Back Home</a>
    </div>
</body>

OdeToFood/Views/Home/Index.cshtml
@model HomeIndexVM

@{
    ViewBag.Title = "Restaurant ++";
}

<h1>All restaurants</h1>

@foreach (var restaurant in Model.Restaurants)
{
    @Html.Partial("_Summary", restaurant);
}
<div>
    <a asp-action="Create" asp-controller="Home">Create</a>
</div>

OdeToFood/Views/Home/Update.cshtml
@model Restaurant

@{
    ViewBag.Title = "Update " + Model.Id.ToString();
}

    <h1>Update</h1>
    <form method="post">
        <input type="text" id="Name" name="Name" value="@Model.Name">
        @*<input asp-for = "Name">*@
        <select asp-for="Cuisine" asp-items="Html.GetEnumSelectList<CuisineType>()"></select>
        <input type="submit" name="Save" value="Save" />
    </form>

OdeToFood/Views/Home/_Summary.cshtml
@model Restaurant

<section>
    <h3>@Model.Name</h3>

    <div>
        Cuisine: @Model.Cuisine
    </div>
    <div>
        <a asp-action="Details" asp-route-id="@Model.Id">Details</a>
        <a asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
</section>

OdeToFood/Views/Shared/Components/Greeter/Default.cshtml
@model string

<h1>@Model</h1>

OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <div>
        Copyright: @DateTime.Now.Year
    </div>
    <footer>
        @RenderSection("footer", required:false)
        @*@await Component.InvokeAsync("Greeter")*@
        <vc:greeter></vc:greeter>
    </footer>
</body>
</html>